blueprints/qa.py
from flask import Blueprint,render_template,request,g,redirect,url_for,flash
from decorators import login_required
from .forms import QuestionForm,AnswerForm
from models import QuestionModel,AnswerModel
from exts import db
from sqlalchemy import or_

bp = Blueprint("qa",__name__,url_prefix="/")

@bp.route("/")
def index():
    questions = QuestionModel.query.order_by(db.text("-create_time")).all()
    return render_template("index.html",questions=questions)

@bp.route("/question/public",methods=['GET','POST'])
@login_required
def public_question():
    if request.method=='GET':
        return render_template("public_question.html")
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title,content=content,author=g.user)
            db.session.add(question)
            db.session.commit()
            return redirect("/")
        else:
            flash("标题或内容格式错误")
            return redirect(url_for("qa.public_question"))

@bp.route("/question/<int:question_id>")
def question_detail(question_id):
    question = QuestionModel.query.get(question_id)
    return render_template("detail.html",question=question)

@bp.route("/answer/<int:question_id>",methods=['POST'])
@login_required
def answer(question_id):
    form = AnswerForm(request.form)
    if form.validate():
        content = form.content.data

        answer_model = AnswerModel(content=content,author=g.user,question_id=question_id)

        db.session.add(answer_model)
        db.session.commit()
        return redirect(url_for('qa.question_detail',question_id = question_id))
    else:
        flash("表单验证失败！")
        return redirect(url_for('qa.question_detail',question_id=question_id))

@bp.route("/search")
def search():
    keyword = request.args.get("q")
    #filter-by:直接使用字段的名称
    #filter:使用模型.字段名称
    questions = QuestionModel.query.filter(or_(QuestionModel.title.contains(keyword),QuestionModel.content.contains(keyword))).order_by(db.text("-create_time"))
    return render_template("index.html",questions=questions)

blueprints/user.py
import string
import random
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    jsonify,
    session,
    flash
)
from exts import mail,db
from flask_mail import Message
from models import *
from datetime import datetime
from .forms import RegisterForm,LoginForm
from werkzeug.security import generate_password_hash,check_password_hash


bp = Blueprint("user",__name__,url_prefix="/user")

@bp.route("/login",methods=['GET','POST'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if user and check_password_hash(user.password,password):
                session['user_id'] = user.id
                return redirect("/")
            else:
                flash("邮箱或密码错误")
                return redirect(url_for("user.login"))
        else:
            flash("邮箱或密码格式错误")
            return redirect(url_for("user.login"))


@bp.route("/register",methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():

            email = form.email.data
            username = form.username.data
            password = form.password.data
            hash_password = generate_password_hash(password)
            user = UserModel(email=email, username=username, password=hash_password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("user.register"))
        
@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for('user.login'))

@bp.route("/captcha",methods=['GET', 'POST'])
def get_captcha():
    #GET，POST
    email = request.form.get("email")
    letters = string.ascii_letters + string.digits
    captcha = "".join(random.sample(letters,4))
    print(captcha)
    print(email)
    if email:
        message = Message(
            subject='TEST',
            recipients=[email],
            body=f"【J.A.R.V.I.S】您的验证码是：{captcha}，请不要告诉任何人哦！"
        )
        mail.send(message)
        captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
        if captcha_model:
            captcha_model.captcha = captcha
            captcha_model.create_time = datetime.now()
            db.session.commit()
        else:
            captcha_model = EmailCaptchaModel(email=email,captcha = captcha)
            db.session.add(captcha_model)
            db.session.commit()

    else:
        return jsonify({"code": 400, "message": "请先输入邮箱"})

    return jsonify({"code": 200})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
    {% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/bootstrap@4.6.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/init.css') }}">
    {% block head %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">J.A.R.V.I.S</a>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('qa.public_question') }}">发布问答</a>
      </li>
      <li class="nav-item ml-2">
          <form class="form-inline my-2 my-lg-0" method="GET" action="{{ url_for("qa.search") }}">
          <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search" name="q">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
          </form>
      </li>

    </ul>
      <ul class="navbar-nav">
          {% if user %}
              <li class="nav-item">
                  <span class="nav-link" >{{ user.username }}</span>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{ url_for("user.logout") }}">退出登录</a>
              </li>
          {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
            </li>
          {% endif %}


    </ul>
  </div>
    </div>
</nav>
<div class="container">
    {% block body %}
    {% endblock %}
</div>
</body>
</html> 

templates/base_01.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
    {% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/bootstrap@4.6.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/init.css') }}">
    {% block head %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">J.A.R.V.I.S</a>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('qa.public_question') }}">发布问答</a>
      </li>
      <li class="nav-item ml-2">
          <form class="form-inline my-2 my-lg-0" method="GET" action="{{ url_for("qa.search") }}">
          <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search" name="q">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
          </form>
      </li>

    </ul>
      <ul class="navbar-nav">
          {% if user %}
              <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('user.profile') }}"><img style="height: 25px;width: 25px;" src="{{ url_for('static',filename=user.avatar_path.split('static/')[-1]) }}" alt=""></a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{ url_for("user.logout") }}">退出登录</a>
              </li>
          {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
            </li>
          {% endif %}


    </ul>
  </div>
    </div>
</nav>
<div class="container">
    {% block body %}
    {% endblock %}
</div>
</body>
</html> 

templates/detail.html
{% extends "base.html" %}

{% block title %}
    问答详情
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/detail.css') }}">
{% endblock %}

{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-8" style="background-color: #fff;padding: 20px">
            <h3 class="page-title">{{ question.title }}</h3>
            <p class="question-info">
                <span>作者：{{ question.author.username }}</span>
                <span>时间：{{ question.create_time }}</span>
            </p>
            <hr>
            <p class="question-content">{{ question.content }}</p>
            <hr>
            <h4 class="comment-group-title">评论（{{ question.answers|length }}）：</h4>
            <form action="{{ url_for('qa.answer',question_id=question.id ) }}" method="post">

                <div class="form-group">
                    <input type="text" placeholder="请填写评论" name="content" class="form-control">
                </div>
                {% for message in get_flashed_messages() %}
                    <div class="form-group">
                        <div class="text-danger">{{ message }}</div>
                    </div>
                {% endfor %}
                <div class="form-group" style="text-align: right;">
                    <button class="btn btn-primary" >评论</button>
                </div>
            </form>
            <ul class="comment-group">
                {% for answer in question.answers %}
                    <li>
                    <div class="user-info">
                        <img src="{{ url_for('static',filename='images/avatar.jpg') }}" alt="" class="avatar">
                        <span class="username">{{ answer.author.username }}</span>
                        <span class="create-time">{{ answer.create_time }}</span>
                    </div>
                    <p class="comment-content">{{ answer.content }}</p>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}
J.A.R.V.I.S
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}
{% block body %}
<div class="row" style="margin-top: 20px;">
<div class="col"></div>
<div class="col-8">
    <ul class="question-ul">
        {% for question in questions %}
            <li>
            <div class="side-question">
                <img class="side-question-avatar" src="{{ url_for('static',filename='images/avatar.jpg') }}" alt="">
            </div>
            <div class="question-main">
                <div class="question-title"><a href="{{ url_for('qa.question_detail',question_id=question.id) }} ">{{ question.title }}</a></div>
                <div class="question-content">{{ question.content }}</div>
                <div class="question-detail">
                    <span class="question-author">{{ question.author.username }}</span>
                    <span class="question-time">{{ question.create_time }}</span>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
<div class="col"></div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}
    Login
{% endblock %}
{% block head %}

{% endblock %}
{% block body %}
    <div class="row mt-4">
        <div class="col"></div>
        <div class="col">
            <form action="{{ url_for("user.login") }}" method="POST">
                <div class="form-group">
                    <label for="exampleInputEmail1">邮箱</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                    <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用途</small>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                </div>
                {% for message in get_flashed_messages() %}
                <div class="form-group">
                <div class="text-danger">{{ message }}</div>
                </div>
                {% endfor %}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">立即登录</button>
                </div>

            </form>
        </div>
        <div class="col"></div>
    </div>

{% endblock %}

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/public_question.html
{% extends "base.html" %}

{% block title %}
发布问答
{% endblock %}

{% block body %}
<div class="row" style="margin-top: 20px;">
<div class="col">
</div>
<div class="col-8">
    <h1 style="text-align: center;">发布问答</h1>
    <form action="{{ url_for('qa.public_question') }}" method="post">
         <div class="form-group">
             <input type="text" name="title" placeholder="请输入标题" class="form-control">
         </div>
        <div class="form-group">
            <textarea name="content" class="form-control" cols="30" rows="10" placeholder="请输入内容"></textarea>
         </div>
        {% for message in get_flashed_messages() %}
            <div class="form-group">
                <div class="text-danger">{{ message }}</div>
            </div>
        {% endfor %}
        <div class="form-group" style="text-align: right">
            <button class="btn btn-primary" >发布</button>
        </div>
    </form>
</div>
<div class="col"></div>
</div>

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}
Register
{% endblock %}
{% block head %}
    <script src="{{ url_for('static',filename='jquery/jquery.3.6.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/register.js') }}"></script>
{% endblock %}
{% block body %}
<div class="row mt-4">
        <div class="col"></div>
        <div class="col">
            <form method='POST' action="{{ url_for('user.register') }}">
                <div class="form-group">
                    <label for="exampleInputEmail1">邮箱</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                    <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用途</small>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1">验证码</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="captcha">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                        </div>
                    </div>

                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1">用户名</label>
                    <input type="text" class="form-control" name="username">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">确认密码</label>
                    <input type="password" class="form-control" name="passwprd_confirm">
                </div>

                <button type="submit" class="btn btn-primary">注册</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}